import{a as w,S,i as s}from"./assets/vendor-Do60_h77.js";/* empty css                      */(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const n of e)if(n.type==="childList")for(const i of n.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&r(i)}).observe(document,{childList:!0,subtree:!0});function a(e){const n={};return e.integrity&&(n.integrity=e.integrity),e.referrerPolicy&&(n.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?n.credentials="include":e.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function r(e){if(e.ep)return;e.ep=!0;const n=a(e);fetch(e.href,n)}})();const b="55634424-38cd5244829b570b556fa0f1a",q="https://pixabay.com/api/";async function y(t,o){const a={key:b,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:o};return(await w.get(q,{params:a})).data}let d=null;function v(){const t=document.querySelector(".gallery");t.innerHTML=""}function p(){document.querySelector(".loader").classList.remove("hidden")}function g(){document.querySelector(".loader").classList.add("hidden")}function R({webformatURL:t,largeImageURL:o,tags:a,likes:r,views:e,comments:n,downloads:i}){return`
    <li class="gallery-item">
      <a href="${o}">
        <img src="${t}" alt="${a}" />
      </a>
      <div class="gallery-info">
        <p>Likes: ${r}</p>
        <p>Views: ${e}</p>
        <p>Comments: ${n}</p>
        <p>Downloads: ${i}</p>
      </div>
    </li>
  `}function h(t){const o=document.querySelector(".gallery"),a=t.map(r=>R(r)).join("");o.insertAdjacentHTML("beforeend",a),d?d.refresh():d=new S(".gallery a",{captionsData:"alt",captionDelay:250})}function B(){document.querySelector(".load-more").classList.remove("hidden")}function c(){document.querySelector(".load-more").classList.add("hidden")}const L=document.querySelector(".form"),u=document.querySelector(".load-more");let f="",l=1,m=0;c();L.addEventListener("submit",D);u.addEventListener("click",I);async function D(t){t.preventDefault();const a=new FormData(L).get("query").trim();if(!a){s.error({message:"Please enter a search query!",position:"topRight"});return}f=a,l=1,v(),c(),p();try{const r=await y(f,l);if(m=r.totalHits,r.hits.length===0){s.warning({message:"No images found. Try another query.",position:"topRight"});return}h(r.hits),r.hits.length<15||m<=15?(c(),s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):B()}catch{s.error({message:"Something went wrong. Try again later.",position:"topRight"})}finally{g()}}async function I(){l+=1,p(),u.disabled=!0;try{const t=await y(f,l);h(t.hits),M(),l*15>=m&&(c(),s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{s.error({message:"Something went wrong. Try again later.",position:"topRight"})}finally{g(),u.disabled=!1}}function M(){const t=document.querySelector(".gallery a");if(!t)return;const{height:o}=t.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
