import{a as L,S as w,i as s}from"./assets/vendor-DnoGfDwQ.js";/* empty css                      */(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const n of e)if(n.type==="childList")for(const i of n.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&o(i)}).observe(document,{childList:!0,subtree:!0});function a(e){const n={};return e.integrity&&(n.integrity=e.integrity),e.referrerPolicy&&(n.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?n.credentials="include":e.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function o(e){if(e.ep)return;e.ep=!0;const n=a(e);fetch(e.href,n)}})();const S="55634424-38cd5244829b570b556fa0f1a",q="https://pixabay.com/api/";async function f(t,r){const a={key:S,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:r};return(await L.get(q,{params:a})).data}let d=null;function v(){const t=document.querySelector(".gallery");t.innerHTML=""}function y(){document.querySelector(".loader").classList.remove("hidden")}function g(){document.querySelector(".loader").classList.add("hidden")}function b({webformatURL:t,largeImageURL:r,tags:a,likes:o,views:e,comments:n,downloads:i}){return`
    <div class="gallery-item">
      <a href="${r}">
        <img src="${t}" alt="${a}" />
      </a>
      <div class="gallery-info">
        <p>Likes: ${o}</p>
        <p>Views: ${e}</p>
        <p>Comments: ${n}</p>
        <p>Downloads: ${i}</p>
      </div>
    </div>
  `}function p(t){const r=document.querySelector(".gallery"),a=t.map(o=>b(o)).join("");r.insertAdjacentHTML("beforeend",a),d?d.refresh():d=new w(".gallery a",{captionsData:"alt",captionDelay:250})}function B(){document.querySelector(".load-more").classList.remove("hidden")}function l(){document.querySelector(".load-more").classList.add("hidden")}const h=document.querySelector(".search-form"),D=document.querySelector(".load-more");let u="",c=1,m=0;l();h.addEventListener("submit",I);D.addEventListener("click",M);async function I(t){t.preventDefault();const a=new FormData(h).get("query").trim();if(!a){s.error({message:"Please enter a search query!",position:"topRight"});return}u=a,c=1,v(),l(),y();try{const o=await f(u,c);if(m=o.totalHits,o.hits.length===0){s.warning({message:"No images found. Try another query.",position:"topRight"});return}p(o.hits),o.hits.length<15||o.hits.length===m?l():B()}catch{s.error({message:"Something went wrong. Try again later.",position:"topRight"})}finally{g()}}async function M(){c+=1,y();try{const t=await f(u,c);p(t.hits),R(),c*15>=m&&(l(),s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{s.error({message:"Something went wrong. Try again later.",position:"topRight"})}finally{g()}}function R(){const t=document.querySelector(".gallery a");if(!t)return;const{height:r}=t.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
